/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DifficultyLevel } from './difficultyTypes';

export const DIFFICULTY_LEVELS: Record<number, DifficultyLevel> = {
  1: {
    level: 1,
    timerIntro: 14,
    timerPeak: 12,
    jumpSizeDistribution: { small: 1.0 },
    modifierCountDistribution: { '1': 1.0 },
    modifierMagnitudeDistribution: { '1-2': 1.0 },
    distractorCountDistribution: { '2': 1.0 },
    distractorSimilarityDistribution: { low: 1.0 },
    operandMagnitudeDistribution: { '1': 1.0 },
    memoryPressureProbability: 0.0,
  },
  2: {
    level: 2,
    timerIntro: 12,
    timerPeak: 10,
    jumpSizeDistribution: { small: 0.9, medium: 0.1 },
    modifierCountDistribution: { '1': 0.9, '2': 0.1 },
    modifierMagnitudeDistribution: { '1-2': 0.8, '3': 0.2 },
    distractorCountDistribution: { '2': 1.0 },
    distractorSimilarityDistribution: { low: 1.0 },
    operandMagnitudeDistribution: { '1': 0.8, '2': 0.2 },
    memoryPressureProbability: 0.0,
  },
  3: {
    level: 3,
    timerIntro: 10,
    timerPeak: 8,
    jumpSizeDistribution: { small: 0.8, medium: 0.2 },
    modifierCountDistribution: { '1': 0.7, '2': 0.3 },
    modifierMagnitudeDistribution: { '1-2': 0.6, '3': 0.4 },
    distractorCountDistribution: { '2': 0.5, '3': 0.5 },
    distractorSimilarityDistribution: { low: 0.8, medium: 0.2 },
    operandMagnitudeDistribution: { '1': 0.4, '2': 0.6 },
    memoryPressureProbability: 0.0,
  },
  4: {
    level: 4,
    timerIntro: 8,
    timerPeak: 7,
    jumpSizeDistribution: { small: 0.6, medium: 0.4 },
    modifierCountDistribution: { '1': 0.3, '2': 0.7 },
    modifierMagnitudeDistribution: { '1-2': 0.4, '3': 0.4, '4': 0.2 },
    distractorCountDistribution: { '3': 1.0 },
    distractorSimilarityDistribution: { low: 0.5, medium: 0.5 },
    operandMagnitudeDistribution: { '2': 0.8, '3': 0.2 },
    memoryPressureProbability: 0.0,
  },
  5: {
    level: 5,
    timerIntro: 7,
    timerPeak: 6,
    jumpSizeDistribution: { small: 0.4, medium: 0.5, large: 0.1 },
    modifierCountDistribution: { '1': 0.1, '2': 0.9 },
    modifierMagnitudeDistribution: { '1-2': 0.2, '3': 0.4, '4-5': 0.4 },
    distractorCountDistribution: { '3': 1.0 },
    distractorSimilarityDistribution: { medium: 1.0 },
    operandMagnitudeDistribution: { '2': 0.4, '3': 0.6 },
    memoryPressureProbability: 0.05,
  },
  6: {
    level: 6,
    timerIntro: 6,
    timerPeak: 5,
    jumpSizeDistribution: { small: 0.2, medium: 0.6, large: 0.2 },
    modifierCountDistribution: { '2': 1.0 },
    modifierMagnitudeDistribution: { '1-2': 0.1, '3': 0.3, '4-5': 0.6 },
    distractorCountDistribution: { '3': 1.0 },
    distractorSimilarityDistribution: { medium: 0.5, high: 0.5 },
    operandMagnitudeDistribution: { '3': 0.8, '4': 0.2 },
    memoryPressureProbability: 0.1,
  },
  7: {
    level: 7,
    timerIntro: 5,
    timerPeak: 4.5,
    jumpSizeDistribution: { small: 0.1, medium: 0.6, large: 0.3 },
    modifierCountDistribution: { '2': 0.7, '3': 0.3 },
    modifierMagnitudeDistribution: { '3': 0.2, '4-5': 0.8 },
    distractorCountDistribution: { '3': 0.5, '4': 0.5 },
    distractorSimilarityDistribution: { high: 1.0 },
    operandMagnitudeDistribution: { '3': 0.4, '4': 0.6 },
    memoryPressureProbability: 0.15,
  },
  8: {
    level: 8,
    timerIntro: 4.5,
    timerPeak: 4,
    jumpSizeDistribution: { medium: 0.5, large: 0.5 },
    modifierCountDistribution: { '2': 0.4, '3': 0.6 },
    modifierMagnitudeDistribution: { '3': 0.1, '4-5': 0.9 },
    distractorCountDistribution: { '4': 1.0 },
    distractorSimilarityDistribution: { high: 0.5, 'very high': 0.5 },
    operandMagnitudeDistribution: { '4': 0.8, '5': 0.2 },
    memoryPressureProbability: 0.2,
  },
  9: {
    level: 9,
    timerIntro: 4,
    timerPeak: 3.5,
    jumpSizeDistribution: { medium: 0.3, large: 0.7 },
    modifierCountDistribution: { '3': 0.7, '4': 0.3 },
    modifierMagnitudeDistribution: { '4-5': 1.0 },
    distractorCountDistribution: { '4': 1.0 },
    distractorSimilarityDistribution: { 'very high': 1.0 },
    operandMagnitudeDistribution: { '4': 0.4, '5': 0.6 },
    memoryPressureProbability: 0.3,
  },
  10: {
    level: 10,
    timerIntro: 3.5,
    timerPeak: 3,
    jumpSizeDistribution: { medium: 0.1, large: 0.9 },
    modifierCountDistribution: { '3': 0.3, '4': 0.7 },
    modifierMagnitudeDistribution: { '4-5': 1.0 },
    distractorCountDistribution: { '4': 1.0 },
    distractorSimilarityDistribution: { extreme: 1.0 },
    operandMagnitudeDistribution: { '5': 1.0 },
    memoryPressureProbability: 0.5,
  }
};
